<a href="https://colab.research.google.com/github/NickMattiss/AIML_inlamning1/blob/main/deeplake_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install deeplake

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 390 kB 5.2 MB/s 
     |████████████████████████████████| 132 kB 10.8 MB/s 
     |████████████████████████████████| 79 kB 2.8 MB/s 
     |████████████████████████████████| 6.7 MB 36.9 MB/s 
     |████████████████████████████████| 10.2 MB 28.1 MB/s 
     |████████████████████████████████| 79 kB 5.2 MB/s 
     |████████████████████████████████| 140 kB 27.0 MB/s 
     |████████████████████████████████| 132 kB 59.8 MB/s 
     |████████████████████████████████| 52 kB 812 kB/s 
     |████████████████████████████████| 127 kB 82.1 MB/s 
  Created wheel for deeplake: filename=deeplake-3.1.2-py3-none-any.whl size=469119 sha256=770133afa1b252890028b1ef8d5ac21eb7454b4fee78e544aedf65a6901d0ebc
  Stored in directory: /root/.cache/pip/wheels/5a/68/44/50cf3e52daf85619d0b3af63d6ae8edfab889f29b1a3a4c265
Successfully built deeplake
  Attempting uninstall: urllib3
    F

In [3]:
import deeplake

In [4]:
ds_test = deeplake.load('hub://activeloop/gtsrb-test')

hub://activeloop/gtsrb-test loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/activeloop/gtsrb-test


In [5]:
ds_train = deeplake.load('hub://activeloop/gtsrb-train')

hub://activeloop/gtsrb-train loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/activeloop/gtsrb-train


In [6]:
len(ds_test), len(ds_train)

(7357, 39209)

In [7]:
ds_test.images[0], ds_train.images[0]

(Tensor(key='images', index=Index([0])),
 Tensor(key='images', index=Index([0])))

In [8]:
ds_test.labels[0].numpy(), ds_train.labels[0].numpy()

(array([11], dtype=uint32), array([18], dtype=uint32))

In [13]:
ds_test.labels[0].numpy(), ds_train.labels[0].numpy()

(array([11], dtype=uint32), array([18], dtype=uint32))

In [12]:
ds_test.images[1].shape, ds_train.images[3].shape

((31, 31, 3), (26, 28, 3))

array([11], dtype=uint32)

In [24]:
from PIL import Image

In [31]:
Image.fromarray(ds1.images(0).numpy(), "L")

TypeError: ignored

In [ ]:
import numpy as np
for im in ds1.images:
  print(np.mean(im.numpy()))